---

-   name: Gather os specific variables
    include_vars: '{{ item }}'
    with_first_found:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml'
        - '{{ ansible_distribution }}.yml'

-   name: Ensure Network Time Daemon distribution
    package:
        name: '{{ item }}'
        state: present
    with_items: '{{ ntp_packages }}'

-   name: Ensure Network Time Daemon service
    systemd:
        name: ntpd
        state: started
        enabled: yes
