---

-   include_role:
        name: fileserver
        tasks_from: cache
    vars:
        cache_file: "{{item.file}}"
        cache_url: "{{item.url}}"
    with_items:
        -   file: consul/consul_0.9.2_linux_amd64.zip
            url: https://releases.hashicorp.com/consul/0.9.2/consul_0.9.2_linux_amd64.zip
        -   file: consul/consul_0.9.2_SHA256SUMS
            url: https://releases.hashicorp.com/consul/0.9.2/consul_0.9.2_SHA256SUMS
        -   file: consul/consul_0.9.2_SHA256SUMS.sig
            url: https://releases.hashicorp.com/consul/0.9.2/consul_0.9.2_SHA256SUMS.sig
