---

-   name: Set ethernet adapter
    set_fact:
        adapter: ansible_eth1

# -   debug: var=server_group

-   name: Cache server group information
    setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    with_items: "{{ groups[server_group] }}"
    when: hostvars[item]['ansible_default_ipv4'] is not defined
# -   debug: var=groups[server_group]

-   name: Cache client IP addresses
    set_fact:
        client_ip: "{{ hostvars[inventory_hostname][adapter].ipv4.address }}"
        server_ips: "{{ groups[server_group] | map('extract', hostvars, [adapter, 'ipv4', 'address']) | list }}"
# -   debug: var=client_ip
# -   debug: var=server_ips

-   name: Client Configuration
    set_fact:
        consul_config:
            advertise_addr: "{{ client_ip }}"
            bind_addr: "{{ client_ip }}"
            data_dir: "/var/{{ consul_service }}"
            retry_join: "{{ server_ips }}"
            disable_update_check: True
# -   debug: var=consul_config

-   include: download.yml

-   include: systemd.yml

-   include: dns.yml

# -   name: Install Python packages
#     pip:
#         name: "{{ item }}"
#         state: present
#         extra_args: "--trusted-host {{nexus_host}}"
#     with_items:
#         - python-consul
