---

-   include: download.yml

-   include: systemd.yml

# -   debug:
#         msg: "consul_server: {{consul_server}}"
        
# -   debug:
#         msg: "inventory_hostname: {{inventory_hostname}}"        

-   name: Client Configuration
    set_fact:
        consul_config:
            advertise_addr: "{{inventory_hostname}}"
            bind_addr: "{{inventory_hostname}}"
            data_dir: "/var/{{consul_service}}"
            retry_join: "{{groups['consul_servers']}}"
            disable_update_check: True

# -   debug:
#         msg: "consul_config: {{consul_config | to_json}}"

-   copy:
        content: "{{consul_config | to_nice_json}}"
        dest: "/etc/{{consul_service}}.d/consul.json"
        owner: root
        group: root
        mode: 0755
    notify:
        - consul_restart
