---

-   user:
        name: "{{ consul_user }}"
        comment: "Consul Account"
        state: present
    notify:
        - consul_restart

-   group:
        name: "{{ consul_group }}"
        state: present
    notify:
        - consul_restart

-   yum:
        name: "{{ item }}"
        state: present
    with_items:
        -   unzip
        -   jq
        -   bind-utils
        -   curl
        -   python2-httpie

-   unarchive:
        src: "{{ consul_archive_url }}"
        dest: /usr/bin
        remote_src: True
        creates: "/usr/bin/{{ consul_filename }}"
    notify:
        - consul_restart

-   file:
        path: "/etc/{{ consul_service }}.d"
        owner: root
        group: root
        mode: 0755
        state: directory
    notify:
        - consul_restart

-   file:
        path: "/var/{{ consul_service }}"
        owner: "{{ consul_user }}"
        group: "{{ consul_user }}"
        mode: 0755
        state: directory
    notify:
        - consul_restart
