---

# -   include: download.yml
# 
# -   include: systemd.yml

# -   debug:
#         msg: "consul_server: {{consul_server}}"
        
# -   debug:
#         msg: "inventory_hostname: {{inventory_hostname}}"
