---

-   include: download.yml

-   include: systemd.yml

# -   debug:
#         msg: "consul_server: {{consul_server}}"

-   name: Server Configuration
    set_fact:
        consul_config:
            advertise_addr: "{{ansible_default_ipv4.address}}"
            bind_addr: "{{ansible_default_ipv4.address}}"
            data_dir: "/var/{{consul_service}}"
            server: True
            # TODO: Figure out how to convert to int
            # bootstrap_expect: "{{groups['consul_servers']|length|int}}"
            bootstrap_expect: 3
            retry_join: "{{groups['consul_servers'] | difference(ansible_default_ipv4.address)}}"
            disable_update_check: True
    when: consul_server == True

# -   debug:
#         msg: "consul_config: {{consul_config | to_json}}"

-   name: Client Configuration
    set_fact:
        consul_config:
            advertise_addr: "{{ansible_default_ipv4.address}}"
            bind_addr: "{{ansible_default_ipv4.address}}"
            data_dir: "/var/{{consul_service}}"
            retry_join: "{{groups['consul_servers']}}"
            disable_update_check: True
    when: consul_server == False

# -   debug:
#         msg: "consul_config: {{consul_config | to_json}}"

-   copy:
        content: "{{consul_config | to_nice_json}}"
        dest: "/etc/{{consul_service}}.d/consul.json"
        owner: root
        group: root
        mode: 0755
    notify:
        - consul_restart
