---

# -   debug var=consul_host
# -   debug var=consul_port

-   set_fact:
        consul_url: "http://{{consul_host}}:{{consul_port}}"

-   set_fact:
        consul_service_url: "{{consul_url}}/v1/catalog/service"
