---

-   name: Service Configuration
    set_fact:
        service_config:
            service:
                name: "{{name}}"
                tags: "{{tags|default([])}}"
                address: "{{address|default(None)}}"
                port: "{{port|default(None)|int}}"
                enableTagOverride: "{{enableTagOverride|default(False)}}"
# -   debug: var=service_config

-   copy:
        content: "{{service_config|to_nice_json|regex_replace('\"([0-9]+)\"','\\1')}}"
        dest: "/etc/{{consul_service}}.d/{{name}}.json"
        owner: root
        group: root
        mode: 0755
    notify:
        - consul_restart
