---

-   include: download.yml

-   include: systemd.yml

-   name: Construct advertise_addr
    set_fact:
        advertise_addr: "{{ansible_eth1.ipv4.address}}"
# -   debug: var=advertise_addr

-   name: Construct retry_join
    set_fact:
        retry_join: "{{groups['consul_servers']|map('extract', hostvars, ['ansible_eth1', 'ipv4', 'address'])|list|difference(advertise_addr)}}"
# -   debug: var=retry_join

-   name: Construct bootstrap_expect
    set_fact:
        bootstrap_expect: "{{groups['consul_servers']|length|int}}"
# -   debug: var=bootstrap_expect

-   name: Server Configuration
    set_fact:
        consul_config:
            advertise_addr: "{{advertise_addr}}"
            bind_addr: "{{advertise_addr}}"
            data_dir: "/var/{{consul_service}}"
            server: True
            bootstrap_expect: "{{bootstrap_expect}}"
            # bootstrap_expect: 3
            retry_join: "{{retry_join}}"
            disable_update_check: True
# -   debug: var=consul_config

-   copy:
        content: "{{consul_config|to_nice_json|regex_replace('\"([0-9]+)\"','\\1')}}"
        dest: "/etc/{{consul_service}}.d/consul.json"
        owner: root
        group: root
        mode: 0755
    notify:
        - consul_restart

-   set_fact:
        nexus_host: "10.0.0.12:8081"
                
-   name: Install Python packages
    pip:
        name: "{{ item }}"
        state: present
        extra_args: "--trusted-host {{nexus_host}}"
    with_items:
        - python-consul
