---

-   name: Set ethernet adapter
    set_fact:
        adapter: ansible_eth1

# -   debug: var=server_group

-   name: Cache server group information
    setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    with_items: "{{ groups[server_group] }}"
    when: hostvars[item]['ansible_default_ipv4'] is not defined
# -   debug: var=groups[server_group]

-   name: Cache server IP addresses
    set_fact:
        server_ip: "{{ hostvars[inventory_hostname][adapter].ipv4.address }}"
        server_ips: "{{ groups[server_group] | map('extract', hostvars, [adapter, 'ipv4', 'address']) | list }}"
# -   debug: var=server_ip
# -   debug: var=server_ips

-   name: Construct consul data
    set_fact:
        other_server_ips: "{{ server_ips | difference(server_ip) }}"
        server_count: "{{ groups[server_group] | length | int }}"
# -   debug: var=other_server_ips
# -   debug: var=bootstrap_expect

-   name: Server Configuration
    set_fact:
        consul_config:
            advertise_addr: "{{ server_ip }}"
            bind_addr: "{{ server_ip }}"
            data_dir: "/var/{{ consul_service }}"
            server: True
            bootstrap_expect: "{{ server_count }}"
            retry_join: "{{ other_server_ips }}"
            disable_update_check: True
# -   debug: var=consul_config

-   include: download.yml

-   include: systemd.yml

-   include: dns.yml

# -   name: Install Python packages
#     pip:
#         name: "{{ item }}"
#         state: present
#         extra_args: "--trusted-host {{nexus_host}}"
#     with_items:
#         - python-consul
