---

-   template:
        src: templates/etc/systemd/system/consul.service
        dest: "/etc/systemd/system/{{ consul_service }}.service"
        owner: root
        group: root
        mode: 0640
    notify:
        - consul_systemctl_daemon_reload
        - consul_restart

-   systemd:
        name: "{{ consul_service }}"
        state: started
        enabled: yes

-   template:
        src: templates/etc/profile.d/consul.sh
        dest: "/etc/profile.d/{{ consul_service }}.sh"
        owner: root
        group: root
        mode: 0644

-   copy:
        content: "{{ consul_config | to_json | regex_replace('\"([0-9]+)\"','\\1') }}"
        # TODO: This quotes the bootstrap_expect value.  It should be an int, but gets serialized as a string
        # content: "{{ consul_config | to_nice_json }}"
        dest: "/etc/{{ consul_service }}.d/consul.json"
        owner: root
        group: root
        mode: 0755
    notify:
        - consul_restart
