-   name: nexus_systemctl_daemon_reload
    command: /bin/systemctl daemon-reload

-   name: nexus_restart
    systemd:
        name: "{{nexus_service}}"
        state: restarted

-   name: nexus_wait
    wait_for:
        host: "{{ansible_eth1.ipv4.address}}"
        port: "{{nexus_port}}"
        delay: 10
        state: present
