---

-   yum:
        name: "{{ item }}"
        state: present
    with_items:
        - openssh

-   name: "Lookup ssh dir"
    become_user: "{{ username }}"
    set_fact:
        ssh_dir: "{{ lookup('env','HOME') }}/.ssh"
        
-   name: "Generate SSH keys"
    become_user: "{{ username }}"
    shell: 'ssh-keygen -b 2048 -t rsa -f {{ssh_dir}}/id_rsa -q -N "There and back again!"'
    args:
        creates: "{{ssh_dir}}/id_rsa"
