---

-   name: "Lookup ssh dir"
    set_fact:
        ssh_dir: "{{ lookup('env','HOME') }}/.ssh"
        
-   name: "Generate SSH keys"
    shell: 'ssh-keygen -b 2048 -t rsa -f {{ssh_dir}}/id_rsa -q -N ""'
    args:
        creates: "{{ssh_dir}}/id_rsa"
