---

-   name: "Lookup ssh dir"
    become_user: "{{ username }}"
    set_fact:
        home_dir: "{{ lookup('env','HOME') }}"

# -   debug: var=ssh_hosts

-   name: Import nodes keys
    become_user: "{{ username }}"
    shell: "ssh-keyscan {{ item }}"
    with_items: "{{ ssh_hosts }}"
    changed_when: false
    register: known_host_results
    ignore_errors: yes

-   name: "Update the {{ home_dir }}/.ssh/known_hosts file with nodes"
    become_user: "{{ username }}"
    known_hosts:
        name: "{{ item.item }}"
        key: "{{ item.stdout }}"
        path: "{{ home_dir }}/.ssh/known_hosts"
    with_items: "{{ known_host_results.results }}"
