---

-   name: Gather os specific variables
    include_vars: '{{ item }}'
    with_first_found:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml'
        - '{{ ansible_distribution }}.yml'

-   name: "Lookup gpg dir"
    become_user: "{{ username }}"
    set_fact:
        gpg_dir: "{{ lookup('env','HOME') }}/.gnupg"

-   name: "Generate GPG keys"
    become_user: "{{ username }}"
    shell: "{{ gpg_exe }} --batch --passphrase '{{ gpg_passphrase }}' --quick-generate-key '{{ eiab_gpg_userid }}' {{ gpg_algo }} {{ gpg_usage }} {{ gpg_expire }}"
    args:
        creates: "{{ gpg_dir }}"
