---

-   name: Install GPG and dependencies
    package:
        name: "{{ item }}"
        state: present
    with_items:
        - gnupg2
        - rng-tools
        - pass

-   include: usershelld.yml

-   include: genkey.yml
