---

-   name: Install GPG and dependencies
    yum:
        name: "{{ item }}"
        state: present
    with_items:
        - gnupg2
        - rng-tools
        - expect
        - pass
        
# -   name: Configure gpg-agent startup script
#     template:
#         src: templates/etc/profile.d/gpg.sh
#         dest: "/etc/profile.d/gpg.sh"
#         owner: root
#         group: root
#         mode: 0644
