---

-   name: register nexus service with the local consul agent
    consul:
        service_name: nexus
        service_address: "{{ansible_eth1.ipv4.address}}"
        service_port: "{{nexus_port}}"
        state: present
