---

-   nexus_repo:
        username: "{{nexus_api_username}}"
        password: "{{nexus_api_password}}"
        host: "{{ansible_eth1.ipv4.address}}:{{nexus_port}}"
        name: releases.hashicorp.com3
        remote_url: https://releases.hashicorp.com
    register: result
-   debug: var=result
