---

-   name: "Install nexus dependencies"
    yum:
        name: "{{ item }}"
        state: present
    with_items:
        - java-1.8.0-openjdk
        - tar

-   user:
        name: "{{nexus_user}}"
        comment: "Nexus Account"
        state: present
    notify:
        - nexus_restart
        - nexus_wait

-   group:
        name: "{{nexus_group}}"
        state: present
    notify:
        - nexus_restart
        - nexus_wait

-   set_fact:
        nexus_home: "/usr/lib/nexus/nexus-{{nexus_version}}"

-   file:
        path: /usr/lib/nexus
        owner: root
        group: root
        mode: 0755
        state: directory
        
-   unarchive:
        src: http://download.sonatype.com/nexus/3/nexus-3.5.0-02-unix.tar.gz
        dest: /usr/lib/nexus
        remote_src: True
        creates: "{{nexus_home}}"

-   template:
        src: templates/usr/lib/nexus/nexus/bin/nexus.rc
        dest: "{{nexus_home}}/bin/nexus.rc"
        owner: root
        group: root
        mode: 0644

-   file:
        path: "/usr/lib/nexus/sonatype-work"
        owner: "{{nexus_user}}"
        group: "{{nexus_group}}"
        mode: 0755
        state: directory
        recurse: yes
    # notify:
    #     - nexus_restart
    #     - nexus_wait

-   include: profiled.yml

-   include_role:
        name: sysctl
        tasks_from: ulimit
    vars:
        username: "{{nexus_user}}"
        type: "-"
        item: nofile
        value: 65536
    notify:
        - nexus_restart
        - nexus_wait 

-   include: systemd.yml

-   systemd:
        name: "{{nexus_service}}"
        state: started
        enabled: yes
