-   name: consul_systemctl_daemon_reload
    command: /bin/systemctl daemon-reload

-   name: consul_restart
    # debug: msg="consule_restart"
    systemd:
        name: "{{consul_service}}"
        state: restarted

-   name: dnsmasq_restart
    systemd:
        name: dnsmasq
        state: restarted

-   name: setup_reload
    setup:
        filter: ansible_local
