---

-   file:
        path: "{{fileserver_dir}}/{{cache_file | dirname}}"
        owner: root
        group: root
        mode: 0755
        state: directory

-   name: download foo.conf
    get_url:
        url: "{{cache_url}}"
        dest: "{{fileserver_dir}}/{{cache_file}}"
        mode: 0755
