---

-   name: Install nginx
    yum:
        name: nginx
        state: present

-   name: Start and enable nginx
    systemd:
        name: nginx
        state: started
        enabled: yes

-   template:
        src: templates/usr/share/nginx/html/index.html
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: 0644

-   file:
        path: "{{fileserver_dir}}"
        owner: root
        group: root
        mode: 0755
        state: directory

# -   template:
#         src: templates/etc/nginx/conf.d/fileserver.conf
#         dest: /etc/nginx/conf.d/fileserver.conf
#         owner: root
#         group: root
#         mode: 0644
#     notify:
#         - nginx_restart

-   template:
        src: templates/etc/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
    notify:
        - nginx_restart
