-   name: Install EPEL repository
    yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

-   name: Install RPM packages
    yum:
        name: "{{ item }}"
        state: present
    with_items:
        - coreutils
        - grep
        - sed
        - gawk
        - bash
        - fish
        - htop
        - jq
        - traceroute
        - telnet
        - expect
        - tar
        - unzip
        - tree
        - tcping
        - yum-utils
        - git
        - iputils
        - net-tools
        - fish
        - openssh-clients
        - bind-utils
        - vim
        - python2-httpie
        - pwgen
        - gnupg2
