---

-   include: common.yml

-   name: Install RPM packages
    yum:
        name: "{{ item }}"
        state: present
    with_items:
        - ruby

-   name: Install Python packages
    pip:
        name: "{{ item }}"
        state: present
    with_items:
        - sphinx
