---

-   set_fact:
        nexus_host: "10.0.0.12"

-   include: common.yml

-   name: Install RPM packages
    yum:
        name: "{{ item }}"
        state: present
    with_items:
        - ruby

-   name: Install Python packages
    pip:
        name: "{{ item }}"
        state: present
        extra_args: "--trusted-host {{nexus_host}}"
    with_items:
        - sphinx
        - sphinx_rtd_theme
        - python-consul
        - rerun
