---

-   name: Install RPM packages
    yum:
        name: "{{ item }}"
        state: present
    with_items:
        - python2-pip

-   name: Install Python packages
    pip:
        name: "{{ item }}"
        state: present
    with_items:
        - sphinx
        - sphinx_rtd_theme
        - python-consul
        - rerun
        # - mkdocs
