---

-   set_fact:
        nexus_host: "10.0.0.12:8081"
# -   debug: var=nexus_host

-   find: 
        path: "/etc/yum.repos.d/" 
        file_type: file
        recurse: yes
    register: files_results
# -   debug: var=files_results

-   file: 
        state: absent 
        path: "{{ item.path }}"
    with_items: 
        - "{{ files_results.files }}"

-   yum_repository:
        name: centos
        description: centos
        baseurl: "http://{{nexus_host}}/repository/centos-base-7-x86_64/"
        gpgcheck: no

-   yum_repository:
        name: epel
        description: centos
        baseurl: "http://{{nexus_host}}/repository/epel-7-x86_64/"
        gpgcheck: no
