-   name: Install common utilities
    hosts: localhost
    connection: local
    become: yes

    tasks:
    
        -   include_role:
                name: utilities
                tasks_from: control
