-   name: Generate ssh keypair
    hosts: localhost
    connection: local
    become: yes

    tasks:
        -   include_role:
                name: ssh
                tasks_from: genkey
        
        -   include_role:
                name: ssh
                tasks_from: import_known_hosts
            vars:
                ssh_hosts: "{{groups['all']}}"
