-   name: Generate ssh keypair
    hosts: localhost
    connection: local
    become: yes

    vars:
        -   p_username: vagrant
        -   p_real_name: "Vagrant Baggins"
        -   p_email: vagrant@eiab.net
        -   p_passphrase: aaaa1234

    tasks:
        
        -   include_role:
                name: keychain
        
        -   include_role:
                name: keychain
                tasks_from: profiled
            vars:
                username: vagrant
