-   name: Generate ssh keypair
    hosts: localhost
    connection: local
    become: yes

    tasks:
        -   include_role:
                name: gpg
        
        -   include_role:
                name: gpg
                tasks_from: gen_key_auto
            vars:
                username: vagrant
                real_name: "Some User"
                email: someone@somewhere.com
        
        -   include_role:
                name: gpg
                tasks_from: gpg_agent_conf
            vars:
                username: vagrant
        
        -   include_role:
                name: keychain
        
        -   include_role:
                name: keychain
                tasks_from: profiled
            vars:
                username: vagrant
