-   name: Control node ssh configuration
    hosts: localhost
    connection: local
    become: yes

    vars:
        ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"
        
    tasks:

        -   name: ssh-keyscan all inventory hosts
            shell: "ssh-keyscan {{ item }}"
            with_items: "{{ groups['all'] }}"
            register: ssh_known_host_results
            ignore_errors: yes
        
        -   name: Update the '{{ ssh_known_hosts_file }}' file with inventory hosts
            known_hosts:
                name: "{{ item.item }}"
                key: "{{ item.stdout }}"
                path: "{{ ssh_known_hosts_file }}"
            with_items: "{{ ssh_known_host_results.results }}"
