---

# -   name: Import ssh host information
#     hosts: localhost
#     connection: local
#     become: yes

#     tasks:

#         -   include_role:
#                 name: eiab
#                 tasks_from: ansible-hosts

-   name: Configure ansible account
    hosts: bootstrap
    become: yes
    gather_facts: false

    tasks:

        -   include_role:
                name: eiab
                tasks_from: ansible-ensure-account

