-   name: Configure ansible account
    hosts: bootstrap
    become: yes

    vars:
        -   ansible_account: ansible
        -   ssh_dir: "{{ lookup('env','HOME') }}/.ssh"
        -   ssh_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    tasks:

        -   user:
                name: "{{ ansible_account }}"
                comment: "Ansible Account"
                state: present
        
        -   include_role:
                name: sudoer
            vars:
                account: "{{ ansible_account }}"

        -   authorized_key:
                user: "{{ ansible_account }}"
                state: present
                key: "{{ ssh_key }}"
