-   name: Generate ssh keypair
    hosts: localhost
    connection: local
    become: yes

    vars:
        ssh_hosts: "{{ groups['all'] }}"

    tasks:
        -   include_role:
                name: eiab
                tasks_from: control-node-ssh

