-   name: Generate ssh keypair
    hosts: localhost
    connection: local
    become: yes

    vars:
        username: vagrant
        ssh_hosts: "{{ groups['all'] }}"

    tasks:
        -   include_role:
                name: ssh

