-   name: Configure vault service
    hosts: vault_clients
    become: yes

    tasks:
    
        -   include_role:
                name: vault
                tasks_from: client

-   name: Configure vault service
    hosts: localhost
    connection: local
    become: yes

    tasks:
    
        -   include_role:
                name: vault
                tasks_from: client
