# ~/.bash_logout

# User specific logout procedures

for i in ~/.config/bash_logout.d/*.bash ; do
    if [ -r "$i" ]; then
        if [ "${-#*i}" != "$-" ]; then
            . "$i"
        else
            . "$i" >/dev/null
        fi
    fi
done
