---

-   set_fact:
        nexus_host: "10.0.0.12:8081"
# -   debug: var=nexus_host

-   set_fact:
        nexus_root: "http://{{nexus_host}}/repository/releases.hashicorp.com"
# -   debug: var=nexus_root

-   name: "Download vault dependencies"
    yum:
        name: "{{ item }}"
        state: present
    with_items:
        - unzip

-   unarchive:
        src: "{{nexus_root}}/vault/0.8.1/vault_0.8.1_linux_amd64.zip"
        dest: /usr/bin
        remote_src: True
        creates: "/usr/bin/{{consul_filename}}"
    notify:
        - vault_restart
