---

-   user:
        name: "{{ vault_user }}"
        comment: "Vault Account"
        state: present
    notify:
        - vault_restart

-   group:
        name: "{{ vault_group }}"
        state: present
    notify:
        - vault_restart

-   name: "Download vault dependencies"
    yum:
        name: "{{ item }}"
        state: present
    with_items:
        -   unzip
        -   jq
        -   bind-utils
        -   curl
        -   python2-httpie

-   unarchive:
        src: "{{ vault_archive_url }}"
        dest: /usr/bin
        remote_src: True
        creates: "/usr/bin/{{ vault_filename }}"
    notify:
        - vault_restart

-   capabilities:
        path: "/usr/bin/{{ vault_filename }}"
        capability: CAP_IPC_LOCK+ep
        state: present
    notify:
        - vault_restart

-   file:
        path: "/etc/{{ vault_service }}.d"
        owner: root
        group: root
        mode: 0755
        state: directory
    notify:
        - vault_restart
