---

-   include: download.yml

-   include: systemd.yml

-   name: Server Configuration
    set_fact:
        vault_config:
            storage:
                consul:
                    address: 127.0.0.1:8500
                    path: vault
            listener:
                tcp:
                    address: "127.0.0.1:{{vault_port}}"
                    tls_disable: 1

-   copy:
        content: "{{vault_config | to_nice_json}}"
        dest: "/etc/{{vault_service}}.d/vault.json"
        owner: root
        group: root
        mode: 0755
    notify:
        - vault_restart

# -   set_fact:
#         consul_acl:
#             key:
#                 "vault/":
#                     policy: write
#             service:
#                 vault:
#                     policy: write
#             service:
#                 vault:
#                     policy: read
#
# -   include_role:
#         name: consul
#         tasks_from: config
#     vars:
#         config_file: vault
#         config_content: "{{consul_acl}}"
