---

-   template:
        src: templates/etc/systemd/system/vault.service
        dest: "/etc/systemd/system/{{ vault_service }}.service"
        owner: root
        group: root
        mode: 0640
    notify:
        - vault_systemctl_daemon_reload
        - vault_restart

-   copy:
        content: "{{ vault_config | to_nice_json }}"
        dest: "/etc/{{ vault_service }}.d/vault.json"
        owner: root
        group: root
        mode: 0755
    notify:
        - vault_restart

-   systemd:
        name: "{{ vault_service }}"
        state: started
        enabled: yes
