-   name: Configure Consul
    hosts: all
    become: yes

    vars:
        - consul_account: consul

    tasks:

        -   user:
                name: "{{ansible_account}}"
                comment: "Ansible Account"
                state: present

        -   authorized_key:
                user: "{{ansible_account}}"
                state: present
                key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

        -   template:
                src: templates/etc/sudoers.d/ansible
                dest: "/etc/sudoers.d/{{ansible_account}}"
                owner: root
                group: root
                mode: 0440
