---

consul_user: consul
consul_group: consul
consul_service: consul
consul_filename: consul
consul_download: https://releases.hashicorp.com/consul/0.9.2/consul_0.9.2_linux_amd64.zip
consul_checksum: https://releases.hashicorp.com/consul/0.9.2/consul_0.9.2_SHA256SUMS
consul_server: False
consul_port: 8500
