---
vault_archive_url: https://releases.hashicorp.com/vault/0.9.0/vault_0.9.0_linux_amd64.zip
vault_user: vault
vault_group: vault
vault_service: vault
vault_filename: vault
vault_port: 8200
vault_host: 127.0.0.1
