---

-   name: Setting variables
    set_fact:
        boot_volume: /Volumes/boot
        
-   name: Enable SSH
    file: 
        path: '{{ boot_volume }}/ssh'
        state: touch
        mode: 0777
