---

-   name: Setting variables
    set_fact:
        download_dir: /tmp/rpi
        imgfile: 2018-04-18-raspbian-stretch-lite.img
        device_path: /dev/disk1
        boot_volume: /Volumes/boot

-   name: Unmount SD card
    shell: 'diskutil unmountDisk {{ device_path }}'

-   name: Create image on SD card
    shell: 'dd bs=1m if={{ download_dir }}/{{ imgfile }} of={{ device_path }} conv=sync'
    become: yes

-   name: Mount SD card
    shell: 'diskutil mountDisk {{ device_path }}'

-   name: Enable SSH
    file: 
        path: '{{ boot_volume }}/ssh'
        state: touch
        mode: 0777
