site_name: Enterprise in a Box
theme: readthedocs
repo_url: https://github.com/boundedinfinity/eiab
markdown_extensions:
    -   admonition
pages:
    - Home: index.md
    - Guide:
        -   'Introduction': 'guide/intro.md'
        -   'Raspberry PI': 'guide/rpi.md'
        -   'macOS': 'guide/macos.md'
        -   'Project Source': 'guide/source.md'
        -   'Machine Image': 'guide/machine-image.md'
        -   'Virtual Machines': 'guide/vagrant.md'
        -   'Control node': 'guide/control-node.md'
        -   'Ansible': 'guide/ansible.md'
        -   'All nodes': 'guide/all-nodes.md'
        -   'Consul': 'guide/consul.md'
        -   'Vault': 'guide/vault.md'
    - Tools:
        -   'ab': 'tools/ab.md'
        -   'Ansible': 'tools/ansible.md'
        -   'Atom': 'tools/atom.md'
        -   'Cassandra': 'tools/cassandra.md'
        -   'Consul': 'tools/consul.md'
        -   'curl': 'tools/curl.md'
        -   'dig': 'tools/dig.md'
        -   'Docker': 'tools/docker.md'
        -   'Git': 'tools/git.md'
        -   'GPG': 'tools/gpg.md'
        -   'Homebrew': 'tools/homebrew.md'
        -   'HTTPie': 'tools/httpie.md'
        -   'jq': 'tools/jq.md'
        -   'Keychain': 'tools/keychain.md'
        -   'Kong': 'tools/kong.md'
        -   'Make': 'tools/make.md'
        -   'MkDocs': 'tools/mkdocs.md'
        -   'Nexus': 'tools/nexus.md'
        -   'Packer': 'tools/packer.md'
        -   'pass': 'tools/pass.md'
        -   'Prometheus': 'tools/prometheus.md'
        -   'Ruby': 'tools/ruby.md'
        -   'SSH': 'tools/ssh.md'
        -   'systemd': 'tools/systemd.md'
        -   'UserShellD': 'tools/usershelld.md'
        -   'Vagrant': 'tools/vagrant.md'
        -   'Vault': 'tools/vault.md'
        -   'YUM': 'tools/yum.md'
    - About: about.md
