---

-   package:
        name: "{{ item }}"
        state: present
    with_items:
        - bash

-   name: "Ensure bash .d directories"
    file:
        path: "{{ usershelld_home }}/{{ item }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
        state: directory
    with_items:
        -   bash/bash_profile.d/available
        -   bash/bash_profile.d/enabled
        -   bash/bashrc.d/available
        -   bash/bashrc.d/enabled
        -   bash/bash_logout.d/available
        -   bash/bash_logout.d/enabled
        -   bash/profile.d/available
        -   bash/profile.d/enabled

-   name: "Ensure bash config directories"
    file:
        path: "{{ bash_config_home }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
        state: directory

-   name: "Ensure bash configuration files"
    template:
        src: "templates/home/user/.config/bash/{{ item }}"
        dest: "{{ bash_config_home }}/{{ item }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0644
        backup: yes
    with_items:
        -   bashrc
        -   bash_profile
        -   bash_logout

-   name: "Ensure bash configuration symlinks"
    file:
        src: "{{ bash_config_home }}/{{ item }}"
        dest: "{{ user_home }}/.{{ item }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: 0755
        state: link
        backup: yes
        force: yes
    with_items:
            -   bashrc
            -   bash_profile
            -   bash_logout

-   include: bash_profile.yml
    vars:
        script_src: templates/home/user/.config/usershelld/bash/bash_profile.d/available/home-bin.bash
