---

-   name: 'Configure fish login script'
    include: fish-login.yml
    vars:
        script_name: 'ssh-agent.fish'

-   name: 'Configure fish logout script'
    include: fish-logout.yml
    vars:
        script_name: 'ssh-agent.fish'
